my_string=input("Столица России: ")
print(my_string)
m_string=my_string.replace(" ","")
print(len(m_string))
print('Cтолица России: '.upper())
print("Столица России: ".lower())
print(my_string[0])
print(my_string[-1])
